version: "3.9"
services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "1296:3000"
  prometheus:
    image: prom/prometheus:latest
    command:
      - --config.file=/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
  myserver_node_exporter:
    image: prom/node-exporter:latest
    ports:
      - "9100:9100"
